server:
  port : 8085

spring:
  cloud:
    function:
      definition: transactionJoiner;
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          contentType: application/json
        transactionJoiner-in-0:
          destination: transaction-init-topic
        transactionJoiner-in-1:
          destination: transaction-detail-enriched-topic
        transactionJoiner-in-2:
          destination: account-enriched-topic
        transactionJoiner-out-0:
          destination: transaction-joined-topic

process:
  join-window-duration: 5h
  grace-window-duration: 2h
